### ISSUE TITLE
datetime 필드 일괄 포맷 변경

### ISSUE THREAD

**Issue by dadahee** [kookmin-sw/capstone-2022-24#198]
## 세부사항
- `%Y-%m-%d %H:%M:%S`으로 통일

## 참고
- `2022-05-17T07:47:23.247197` -> `2022-05-17 07:47:23`으로 어여쁘게 수정
- 기존 설계서랑 달라 이슈 달아둘게욥.. 필요 없으면(?) 말씀해주세요!

## 관련 이슈
- @a-sung, @yesslee

**Comment by a-sung** [comment]
헐 너무 좋아요ㅠㅠ

**Comment by yesslee** [comment]
헉 지금확인햇어요ㅜ 포맷 완전 깔끔해진거 짱이에요~~!!
